# Auto-exported from 03_content-style_clustering.ipynb
# Generated by assistant


# --- Markdown cell 0 ---
# # 03 Content Style Clustering
# 
# Goal: group posts by **how captions are written** and profile each style cluster.
# 


# --- Code cell 1 ---
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score, adjusted_rand_score
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from collections import Counter
from IPython.display import display
plt.style.use('seaborn-v0_8-whitegrid')
pd.set_option('display.max_colwidth', 200)


# --- Markdown cell 2 ---
# ## Load Data
# 


# --- Code cell 3 ---
try:
    # 
    df = pd.read_json(r"C:\users\hanib\data_mining -project\marketing\data\processed\kpi_dataset.json")
except ValueError:
    df = pd.read_json(r"C:\users\hanib\data_mining -project\marketing\data\processed\kpi_dataset.json", lines=True)
print(df.shape)
display(df.head(3))


# --- Markdown cell 4 ---
# ## Simple EDA
# 


# --- Code cell 5 ---
print('Columns:')
print(df.columns.tolist())
print('Missing values:')
display(df.isna().sum().to_frame('missing_count'))
# engagement rate used later for cluster quality comparison
if 'engagement_rate' not in df.columns:
    df['engagement_rate'] = (df['likes_count'].fillna(0) + df['comments_count'].fillna(0)) / df['followers_count'].replace(0, np.nan)
    df['engagement_rate'] = df['engagement_rate'].fillna(0)
print('Engagement rate summary:')
display(df['engagement_rate'].describe())


# --- Markdown cell 6 ---
# ## Prepare Features For Clustering
# 
# Using engineered content-style features only (no GMM).
# 


# --- Code cell 7 ---
work = df.copy()

feature_cols = [
    'caption_length',
    'hashtags_count',
    'emoji_count',
    'CTA_present',
    'promo_post',
    'mentions_location',
    'religious_theme',
    'patriotic_theme',
    'arabic_dialect_style',
    'discount_percent'
]

# Robust binary normalizer for mixed JSON values (bool/int/yes-no/text labels)
def to_binary_flag(s):
    if s is None:
        return 0
    if isinstance(s, (int, float)) and not pd.isna(s):
        return int(s != 0)
    txt = str(s).strip().lower()
    if txt in {'1','true','yes','y','present','on'}:
        return 1
    if txt in {'0','false','no','n','none','nan',''}:
        return 0
    # For text categories like 'Levantine Arabic', treat non-empty as present
    return 1

for c in ['CTA_present','promo_post','mentions_location','religious_theme','patriotic_theme','arabic_dialect_style']:
    if c in work.columns:
        work[c] = work[c].apply(to_binary_flag).astype(int)
    else:
        work[c] = 0

# numeric conversion
for c in ['caption_length','hashtags_count','emoji_count','discount_percent']:
    if c in work.columns:
        work[c] = pd.to_numeric(work[c], errors='coerce')
    else:
        work[c] = np.nan

# keep more rows: fill instead of dropping heavily
work['caption_length'] = work['caption_length'].fillna(work['caption_length'].median())
work['hashtags_count'] = work['hashtags_count'].fillna(0)
work['emoji_count'] = work['emoji_count'].fillna(0)
work['discount_percent'] = work['discount_percent'].fillna(0)

# final safety fill for any remaining feature nulls
for c in feature_cols:
    if work[c].dtype.kind in 'biufc':
        work[c] = work[c].fillna(work[c].median())
    else:
        work[c] = work[c].fillna(0)

print('Total rows before prep:', len(df))
print('Missing per feature after fill:')
display(work[feature_cols].isna().sum().to_frame('missing'))

X = work[feature_cols].copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print('Rows used for clustering:', len(work))
print('Feature matrix shape:', X_scaled.shape)



# --- Markdown cell 8 ---
# ## KMeans (Elbow + Silhouette)
# 


# --- Code cell 9 ---
inertias = []
sils = []
K = range(2, min(11, len(X_scaled)))
for k in K:
    km = KMeans(n_clusters=k, random_state=42, n_init=20)
    labels = km.fit_predict(X_scaled)
    inertias.append(km.inertia_)
    sils.append(silhouette_score(X_scaled, labels))
fig, ax = plt.subplots(1, 2, figsize=(12, 4))
ax[0].plot(list(K), inertias, marker='o')
ax[0].set_title('Elbow Method')
ax[0].set_xlabel('k')
ax[0].set_ylabel('Inertia')
ax[1].plot(list(K), sils, marker='o', color='darkgreen')
ax[1].set_title('Silhouette by k')
ax[1].set_xlabel('k')
ax[1].set_ylabel('Silhouette score')
plt.tight_layout()
plt.show()
best_k = list(K)[int(np.argmax(sils))]
print('Best k by silhouette:', best_k)


# --- Markdown cell 10 ---
# ## Fit Final KMeans Model
# 


# --- Code cell 11 ---
final_kmeans = KMeans(n_clusters=5, random_state=42, n_init=20)
work['cluster'] = final_kmeans.fit_predict(X_scaled)
cluster_sizes = work['cluster'].value_counts().sort_index().to_frame('posts_count')
display(cluster_sizes)
overall_sil = silhouette_score(X_scaled, work['cluster']) if work['cluster'].nunique() > 1 else np.nan
print('Final silhouette score:', round(float(overall_sil), 4))


# --- Markdown cell 12 ---
# ## t-SNE Visualization
# 


# --- Code cell 13 ---
# keep perplexity valid for small datasets
perplexity = max(5, min(30, len(work)//10))
tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=perplexity,
    learning_rate='auto',
    init='pca'
)
X_tsne = tsne.fit_transform(X_scaled)
work['tsne_1'] = X_tsne[:, 0]
work['tsne_2'] = X_tsne[:, 1]
plt.figure(figsize=(10, 6))
sns.scatterplot(data=work, x='tsne_1', y='tsne_2', hue='cluster', palette='tab10', s=60, alpha=0.85)
plt.title(f't-SNE of Content Style Clusters (k={best_k}, perplexity={perplexity})')
plt.legend(title='Cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()


# --- Markdown cell 14 ---
# ## Cluster Profiling
# 
# For each cluster:
# - average engagement
# - top words
# - top hashtags
# - sample captions
# 


# --- Code cell 15 ---
# helpers
arabic_english_token = re.compile(r"[A-Za-z؀-ۿ]{2,}")
hashtag_re = re.compile(r"#\w+")
stop_words = {
    'the','and','for','with','this','that','from','your','you','our','are','was','have','has',
    '??','??','???','???','???','??','??','???','???','???','??','??','??','??'
}
def top_words(series, n=10):
    tokens = []
    for t in series.fillna(''):
        toks = [x.lower() for x in arabic_english_token.findall(str(t))]
        toks = [x for x in toks if x not in stop_words]
        tokens.extend(toks)
    return Counter(tokens).most_common(n)
def top_hashtags(series, n=10):
    tags = []
    for t in series.fillna(''):
        tags.extend([x.lower() for x in hashtag_re.findall(str(t))])
    return Counter(tags).most_common(n)
profile = work.groupby('cluster').agg(
    posts_count=('cluster', 'size'),
    avg_engagement_rate=('engagement_rate', 'mean'),
    avg_caption_length=('caption_length', 'mean'),
    avg_hashtags=('hashtags_count', 'mean'),
    avg_emoji=('emoji_count', 'mean'),
    cta_rate=('CTA_present', 'mean'),
    promo_rate=('promo_post', 'mean'),
    location_mention_rate=('mentions_location', 'mean'),
    avg_discount=('discount_percent', 'mean')
).reset_index().sort_values('cluster')
# convert rates to percent for readability
for c in ['cta_rate','promo_rate','location_mention_rate']:
    profile[c] = (profile[c] * 100).round(1)
profile['avg_engagement_rate'] = profile['avg_engagement_rate'].round(4)
print('Cluster summary table')
display(profile)
for cid in sorted(work['cluster'].unique()):
    sub = work[work['cluster'] == cid]
    print(f"===== Cluster {cid} =====")
    print('Top words:', top_words(sub['caption_text'], n=8))
    print('Top hashtags:', top_hashtags(sub['caption_text'], n=8))
    print('Sample captions:')
    samples = sub['caption_text'].dropna().head(5).tolist()
    for i, s in enumerate(samples, 1):
        print(f"{i}. {s}")


# --- Markdown cell 16 ---
# ## Fixed DBSCAN (Separate From Constrained Clustering)
# 
# This is a true DBSCAN run, independent from the constrained top/middle/bottom clustering.
# 


# --- Code cell 17 ---
EPS = 5
MIN_SAMPLES = 15
#EPS = 4.5
#MIN_SAMPLES = 15
perplexity = max(5, min(30, len(X_scaled)//10))
tsne_db = TSNE(
    n_components=2,
    random_state=42,
    perplexity=perplexity,
    learning_rate='auto',
    init='pca'
)
X2_db = tsne_db.fit_transform(X_scaled)

db = DBSCAN(eps=EPS, min_samples=MIN_SAMPLES)
labels = db.fit_predict(X2_db)

work['dbscan_fixed_cluster'] = labels

n_clusters = len(set(labels) - {-1})
noise_ratio = (labels == -1).mean()

print({"eps": EPS, "min_samples": MIN_SAMPLES})
print("n_clusters:", n_clusters, "| noise_ratio:", round(float(noise_ratio), 3))
print(work['dbscan_fixed_cluster'].value_counts().sort_index())

plot_df = work.assign(tsne_1=X2_db[:,0], tsne_2=X2_db[:,1])
plt.figure(figsize=(10,6))
sns.scatterplot(
    data=plot_df,
    x='tsne_1', y='tsne_2',
    hue='dbscan_fixed_cluster',
    palette='tab10',
    s=60, alpha=0.85
)
plt.title(f"Manual DBSCAN (eps={EPS}, min_samples={MIN_SAMPLES})")
plt.legend(title='Cluster', bbox_to_anchor=(1.02,1), loc='upper left')
plt.tight_layout()
plt.show()



# --- Markdown cell 18 ---
# ## Cluster Meaning Report
# 
# Prints an interpretation table for each cluster so you can label styles clearly.
# 


# --- Code cell 19 ---
import re
from collections import Counter
# choose cluster column automatically
cluster_col = None
for c in ['dbscan_fixed_cluster', 'band_cluster', 'cluster', 'dbscan_cluster']:
    if c in work.columns:
        cluster_col = c
        break
if cluster_col is None:
    raise ValueError('No cluster column found in `work`. Run clustering cells first.')
print('Using cluster column:', cluster_col)
arabic_english_token = re.compile(r"[A-Za-z؀-ۿ]{2,}")
hashtag_re = re.compile(r"#\w+")
stop_words = {
    'the','and','for','with','this','that','from','your','you','our','are','was','have','has',
    'in','to','of','is','on','at','by','be','as','it','an','or','we','us','new','now','today','back',
    '??','??','???','???','???','??','??','???','???','??','??','??','??','??','??','??','??','??'
}
def top_words(series, n=10):
    tokens = []
    for t in series.fillna(''):
        toks = [x.lower() for x in arabic_english_token.findall(str(t))]
        toks = [x for x in toks if x not in stop_words]
        tokens.extend(toks)
    return Counter(tokens).most_common(n)
def top_hashtags(series, n=10):
    tags = []
    for t in series.fillna(''):
        tags.extend([x.lower() for x in hashtag_re.findall(str(t))])
    return Counter(tags).most_common(n)
summary = work.groupby(cluster_col).agg(
    posts_count=(cluster_col, 'size'),
    avg_engagement_rate=('engagement_rate', 'mean'),
    avg_caption_length=('caption_length', 'mean'),
    avg_hashtags=('hashtags_count', 'mean'),
    avg_emoji=('emoji_count', 'mean'),
    cta_rate=('CTA_present', 'mean'),
    promo_rate=('promo_post', 'mean'),
    location_mention_rate=('mentions_location', 'mean'),
    avg_discount=('discount_percent', 'mean')
).reset_index().sort_values(cluster_col)
for c in ['cta_rate','promo_rate','location_mention_rate']:
    summary[c] = (summary[c] * 100).round(1)
summary['avg_engagement_rate'] = summary['avg_engagement_rate'].round(4)
summary['avg_caption_length'] = summary['avg_caption_length'].round(1)
summary['avg_hashtags'] = summary['avg_hashtags'].round(2)
summary['avg_emoji'] = summary['avg_emoji'].round(2)
summary['avg_discount'] = summary['avg_discount'].round(2)
print('Cluster summary table:')
display(summary)
for cid in sorted(work[cluster_col].dropna().unique()):
    sub = work[work[cluster_col] == cid]
    print(f"\n===== Cluster {cid} =====")
    print('Posts:', len(sub), '| Avg engagement:', round(float(sub['engagement_rate'].mean()), 4))
    print('Top words:', top_words(sub['caption_text'], 8))
    print('Top hashtags:', top_hashtags(sub['caption_text'], 8))
    print('Sample captions:')
    for i, s in enumerate(sub['caption_text'].dropna().head(5).tolist(), 1):
        print(f"{i}. {s}")


# --- Markdown cell 20 ---
# - Cluster -1 — Mixed Outliers
# 
# Irregular/edge posts: very long captions, very high emoji, medium CTA/promo, moderate location mention, low engagement.
# - Cluster 0 — Quick Promo
# 
# Short promo notices: low CTA, light text/visual richness, high promo but weak push.
# - Cluster 1 — Hard Promo Push
# 
# Mid-long captions, very high CTA + 100% promo, low location mention, includes discount pressure, low engagement.
# - Cluster 2 — Simple Organic Winner
# 
# Very short, low CTA, no promo, light style, strong engagement for a simple format.
# - Cluster 3 — Soft Promo Info
# 
# Mid-length, no CTA, 100% promo, low location mention, informational selling style.
# - Cluster 4 — Campaign Blast
# 
# Very long, dense campaign posts: near-100% CTA + promo + location mention, high volume, low engagement.
# - Cluster 5 — Local Story Winner
# 
# Long, expressive, strong emoji + CTA, medium-high promo, high location mention, highest engagement by far.


# --- Code cell 21 ---
# Requested cluster summary (content-style clustering)
import numpy as np
import pandas as pd

if 'work' not in globals():
    raise ValueError('work not found. Run clustering cells first.')
if 'dbscan_fixed_cluster' not in work.columns:
    raise ValueError('dbscan_fixed_cluster not found. Run DBSCAN fixed clustering cell first.')

summary_df = work.copy()
for c in ['likes_count','comments_count','views_count','followers_count','discount_percent']:
    if c not in summary_df.columns:
        summary_df[c] = 0
summary_df['likes_count'] = pd.to_numeric(summary_df['likes_count'], errors='coerce').fillna(0)
summary_df['comments_count'] = pd.to_numeric(summary_df['comments_count'], errors='coerce').fillna(0)
summary_df['views_count'] = pd.to_numeric(summary_df['views_count'], errors='coerce').fillna(0)
summary_df['followers_count'] = pd.to_numeric(summary_df['followers_count'], errors='coerce').replace(0, np.nan)
summary_df['discount_percent'] = pd.to_numeric(summary_df['discount_percent'], errors='coerce').fillna(0)
if 'engagement_rate' not in summary_df.columns:
    summary_df['engagement_rate'] = ((summary_df['likes_count'] + summary_df['comments_count']) / summary_df['followers_count']).fillna(0)
else:
    summary_df['engagement_rate'] = pd.to_numeric(summary_df['engagement_rate'], errors='coerce').fillna(0)
if 'view_rate' not in summary_df.columns:
    summary_df['view_rate'] = (summary_df['views_count'] / summary_df['followers_count']).fillna(0)
else:
    summary_df['view_rate'] = pd.to_numeric(summary_df['view_rate'], errors='coerce').fillna(0)
if 'comment_rate' not in summary_df.columns:
    summary_df['comment_rate'] = (summary_df['comments_count'] / summary_df['followers_count']).fillna(0)
else:
    summary_df['comment_rate'] = pd.to_numeric(summary_df['comment_rate'], errors='coerce').fillna(0)
if 'view_engagement_rate' not in summary_df.columns:
    summary_df['view_engagement_rate'] = ((summary_df['likes_count'] + summary_df['comments_count']) / summary_df['views_count'].replace(0, np.nan)).fillna(0)
else:
    summary_df['view_engagement_rate'] = pd.to_numeric(summary_df['view_engagement_rate'], errors='coerce').fillna(0)
if 'comments_to_likes_ratio' not in summary_df.columns:
    summary_df['comments_to_likes_ratio'] = (summary_df['comments_count'] / summary_df['likes_count'].replace(0, np.nan)).fillna(0)
else:
    summary_df['comments_to_likes_ratio'] = pd.to_numeric(summary_df['comments_to_likes_ratio'], errors='coerce').fillna(0)
for c in ['CTA_present','promo_post','mentions_location','religious_theme','patriotic_theme','arabic_dialect_style','sponsored']:
    if c not in summary_df.columns:
        summary_df[c] = 0
    summary_df[c] = pd.to_numeric(summary_df[c], errors='coerce').fillna(0)
if 'post_type' not in summary_df.columns:
    summary_df['post_type'] = 'unknown'
pt = summary_df['post_type'].astype(str).str.lower()
summary_df['is_reels'] = pt.str.contains('reel').astype(float)
summary_df['is_images'] = pt.str.contains('image|photo').astype(float)
summary_df['is_carousels'] = pt.str.contains('carousel').astype(float)
cluster_summary_requested = summary_df.groupby('dbscan_fixed_cluster').agg(
    posts_count=('dbscan_fixed_cluster','size'),
    avg_engagement_rate=('engagement_rate','mean'),
    avg_view_rate=('view_rate','mean'),
    avg_comment_rate=('comment_rate','mean'),
    avg_view_engagement_rate=('view_engagement_rate','mean'),
    avg_comments_to_likes_ratio=('comments_to_likes_ratio','mean'),
    percentage_reels=('is_reels','mean'),
    percentage_images=('is_images','mean'),
    percentage_carousels=('is_carousels','mean'),
    avg_likes_count=('likes_count','mean'),
    avg_comments_count=('comments_count','mean'),
    avg_views_count=('views_count','mean'),
    avg_caption_length=('caption_length','mean'),
    avg_hashtags=('hashtags_count','mean'),
    avg_emoji=('emoji_count','mean'),
    cta_rate=('CTA_present','mean'),
    promo_rate=('promo_post','mean'),
    location_mention_rate=('mentions_location','mean'),
    avg_discount=('discount_percent','mean'),
    percentage_religious_theme=('religious_theme','mean'),
    percentage_patriotic_theme=('patriotic_theme','mean'),
    percentage_arabic_dialect_style=('arabic_dialect_style','mean'),
    percentage_sponsored=('sponsored','mean')
).reset_index().sort_values('dbscan_fixed_cluster')
pct_cols = ['percentage_reels','percentage_images','percentage_carousels','cta_rate','promo_rate','location_mention_rate','percentage_religious_theme','percentage_patriotic_theme','percentage_arabic_dialect_style','percentage_sponsored']
for c in pct_cols:
    cluster_summary_requested[c] = (cluster_summary_requested[c] * 100).round(2)
num_cols = [c for c in cluster_summary_requested.columns if c not in ['dbscan_fixed_cluster','posts_count'] + pct_cols]
for c in num_cols:
    cluster_summary_requested[c] = cluster_summary_requested[c].round(4)
display(cluster_summary_requested)


# --- Code cell 22 ---
# Requested 3-5 sample posts per cluster
if 'work' not in globals():
    raise ValueError('work not found. Run clustering cells first.')
if 'dbscan_fixed_cluster' not in work.columns:
    raise ValueError('dbscan_fixed_cluster not found. Run DBSCAN fixed clustering cell first.')
samples_df = work.copy()
required_cols = ['business_name','sector','post_type','caption_text','likes_count','comments_count','views_count','engagement_rate','view_rate','CTA_present','promo_post','mentions_location','religious_theme','patriotic_theme','arabic_dialect_style']
for c in required_cols:
    if c not in samples_df.columns:
        samples_df[c] = np.nan
if samples_df['view_rate'].isna().all():
    f = pd.to_numeric(samples_df.get('followers_count', np.nan), errors='coerce').replace(0, np.nan)
    v = pd.to_numeric(samples_df['views_count'], errors='coerce')
    samples_df['view_rate'] = (v / f).fillna(0)
samples_df['cluster_id'] = samples_df['dbscan_fixed_cluster']
sample_posts_requested = (
    samples_df.sort_values(['dbscan_fixed_cluster','engagement_rate'], ascending=[True, False])
              .groupby('dbscan_fixed_cluster', group_keys=False)
              .head(5)
              .loc[:, ['cluster_id','business_name','sector','post_type','caption_text','likes_count','comments_count','views_count','engagement_rate','view_rate','CTA_present','promo_post','mentions_location','religious_theme','patriotic_theme','arabic_dialect_style']]
)
display(sample_posts_requested)


# --- Code cell 23 ---
# KPI-first policy guard (base dataset stays unchanged)
import pandas as pd, numpy as np

KPI_DATASET_COLUMNS = [
    'business_name','sector','followers_count','post_date','day_of_week','month','post_type','caption_text',
    'caption_length','hashtags_count','emoji_count','likes_count','comments_count','views_count','language',
    'CTA_present','promo_post','mentions_location','religious_theme','patriotic_theme','arabic_dialect_style',
    'sponsored','posting_hour','discount_percent','engagement','engagement_rate','like_rate','comment_rate',
    'view_rate','view_engagement_rate','week','is_video','is_reel','posting_time_bin','caption_length_bin',
    'hashtags_count_bin','emoji_count_bin','engagement_level','business_size_bin','high_engagement','high_view_rate',
    'high_comment_rate'
]

def make_clustering_frame(base_df, needed_cols=None):
    w = base_df.copy()
    if needed_cols is not None:
        for c in needed_cols:
            if c not in w.columns:
                w[c] = np.nan

    if 'engagement_rate' not in w.columns or w['engagement_rate'].isna().all():
        if all(c in w.columns for c in ['likes_count','comments_count','followers_count']):
            f = pd.to_numeric(w['followers_count'], errors='coerce').replace(0, np.nan)
            l = pd.to_numeric(w['likes_count'], errors='coerce').fillna(0)
            cm = pd.to_numeric(w['comments_count'], errors='coerce').fillna(0)
            w['engagement_rate'] = ((l + cm) / f).fillna(0)

    if 'view_rate' not in w.columns or w['view_rate'].isna().all():
        if all(c in w.columns for c in ['views_count','followers_count']):
            f = pd.to_numeric(w['followers_count'], errors='coerce').replace(0, np.nan)
            v = pd.to_numeric(w['views_count'], errors='coerce').fillna(0)
            w['view_rate'] = (v / f).fillna(0)

    if 'comment_rate' not in w.columns or w['comment_rate'].isna().all():
        if all(c in w.columns for c in ['comments_count','followers_count']):
            f = pd.to_numeric(w['followers_count'], errors='coerce').replace(0, np.nan)
            cm = pd.to_numeric(w['comments_count'], errors='coerce').fillna(0)
            w['comment_rate'] = (cm / f).fillna(0)

    if 'view_engagement_rate' not in w.columns or w['view_engagement_rate'].isna().all():
        if all(c in w.columns for c in ['likes_count','comments_count','views_count']):
            v = pd.to_numeric(w['views_count'], errors='coerce').replace(0, np.nan)
            l = pd.to_numeric(w['likes_count'], errors='coerce').fillna(0)
            cm = pd.to_numeric(w['comments_count'], errors='coerce').fillna(0)
            w['view_engagement_rate'] = ((l + cm) / v).fillna(0)

    if 'comments_to_likes_ratio' not in w.columns:
        if all(c in w.columns for c in ['comments_count','likes_count']):
            l = pd.to_numeric(w['likes_count'], errors='coerce').replace(0, np.nan)
            cm = pd.to_numeric(w['comments_count'], errors='coerce').fillna(0)
            w['comments_to_likes_ratio'] = (cm / l).fillna(0)

    return w

if 'df' in globals():
    base_kpi_df = df.copy()
elif 'work' in globals():
    base_kpi_df = work.copy()
elif 'biz' in globals():
    base_kpi_df = biz.copy()
else:
    base_kpi_df = None

if base_kpi_df is not None:
    clustering_work_df = make_clustering_frame(base_kpi_df)
    print('KPI policy ready: base_kpi_df preserved, clustering_work_df created.')
    print('Base shape:', base_kpi_df.shape, '| Work shape:', clustering_work_df.shape)
else:
    print('KPI policy loaded. Run data-loading cell first, then rerun this guard cell.')


# --- Code cell 24 ---
# Export artifacts: coordinates JSON, plots PNGs, notebook as .py
import json
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ---------- Paths (professional layout) ----------
project_root = Path.cwd()
artifacts_dir = project_root / "artifacts" / "content_style_clustering"
json_dir = artifacts_dir / "json"
scripts_dir = artifacts_dir / "scripts"
photos_dir = project_root / "photos" / "content_style_clustering"

for d in [artifacts_dir, json_dir, scripts_dir, photos_dir]:
    d.mkdir(parents=True, exist_ok=True)

if 'work' not in globals():
    raise ValueError("`work` dataframe not found. Run clustering cells first.")

export_df = work.copy()

# ---------- Detect columns ----------
if 'kmeans_cluster' in export_df.columns:
    kmeans_col = 'kmeans_cluster'
elif 'cluster' in export_df.columns:
    kmeans_col = 'cluster'
else:
    kmeans_col = None

if 'dbscan_fixed_cluster' in export_df.columns:
    dbscan_col = 'dbscan_fixed_cluster'
elif 'dbscan_cluster' in export_df.columns:
    dbscan_col = 'dbscan_cluster'
else:
    dbscan_col = None

if {'tsne_1', 'tsne_2'}.issubset(export_df.columns):
    x_col, y_col = 'tsne_1', 'tsne_2'
elif {'map_x', 'map_y'}.issubset(export_df.columns):
    x_col, y_col = 'map_x', 'map_y'
else:
    raise ValueError("No coordinate columns found. Need tsne_1/tsne_2 or map_x/map_y.")

# ---------- DBSCAN params ----------
dbscan_eps = globals().get('EPS', globals().get('DBSCAN_EPS', None))
dbscan_min_samples = globals().get('MIN_SAMPLES', globals().get('DBSCAN_MIN_SAMPLES', None))

# ---------- KMeans params ----------
kmeans_n_clusters = None
if 'final_kmeans' in globals() and hasattr(final_kmeans, 'n_clusters'):
    kmeans_n_clusters = int(final_kmeans.n_clusters)
elif kmeans_col is not None and kmeans_col in export_df.columns:
    # Fallback when model object is not present in memory.
    kmeans_n_clusters = int(export_df[kmeans_col].nunique(dropna=True))

# ---------- Save coordinates + metadata JSON ----------
coord_cols = [x_col, y_col]
base_cols = ['business_name', 'sector', 'post_type']
base_cols = [c for c in base_cols if c in export_df.columns]

payload = {
    'project': 'content_style_clustering',
    'coordinates_type': {'x': x_col, 'y': y_col},
    'dbscan_params': {
        'eps': None if dbscan_eps is None else float(dbscan_eps),
        'min_samples': None if dbscan_min_samples is None else int(dbscan_min_samples),
    },
    'kmeans_params': {
        'n_clusters': kmeans_n_clusters,
    },
    'cluster_columns': {
        'kmeans': kmeans_col,
        'dbscan': dbscan_col,
    },
    'n_rows': int(len(export_df)),
    'records': []
}

keep_cols = base_cols + coord_cols
if kmeans_col is not None:
    keep_cols.append(kmeans_col)
if dbscan_col is not None:
    keep_cols.append(dbscan_col)

for rec in export_df[keep_cols].to_dict(orient='records'):
    clean = {}
    for k, v in rec.items():
        if isinstance(v, (np.integer,)):
            clean[k] = int(v)
        elif isinstance(v, (np.floating, float)):
            clean[k] = float(v)
        elif v is None:
            clean[k] = None
        else:
            clean[k] = v
    payload['records'].append(clean)

json_path = json_dir / 'content_style_cluster_coordinates.json'
with json_path.open('w', encoding='utf-8') as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)

# ---------- Save plots ----------
if kmeans_col is not None:
    plt.figure(figsize=(12, 8))
    sns.scatterplot(data=export_df, x=x_col, y=y_col, hue=kmeans_col, palette='tab10', s=60, alpha=0.85)
    plt.title('Content-Style KMeans Clusters (2D Map)')
    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.legend(title='KMeans Cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    kmeans_plot_path = photos_dir / 'content_style_kmeans_clusters.png'
    plt.savefig(kmeans_plot_path, dpi=300, bbox_inches='tight')
    plt.close()
else:
    kmeans_plot_path = None

if dbscan_col is not None:
    plt.figure(figsize=(12, 8))
    sns.scatterplot(data=export_df, x=x_col, y=y_col, hue=dbscan_col, palette='tab10', s=60, alpha=0.85)
    eps_txt = f"{dbscan_eps}" if dbscan_eps is not None else "N/A"
    ms_txt = f"{dbscan_min_samples}" if dbscan_min_samples is not None else "N/A"
    plt.title(f'Content-Style DBSCAN Clusters (eps={eps_txt}, min_samples={ms_txt})')
    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.legend(title='DBSCAN Cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    dbscan_plot_path = photos_dir / 'content_style_dbscan_clusters.png'
    plt.savefig(dbscan_plot_path, dpi=300, bbox_inches='tight')
    plt.close()
else:
    dbscan_plot_path = None

# ---------- Export notebook to .py ----------
nb_file = Path(r'notebooks/clustering/03_content-style_clustering.ipynb')
py_out = scripts_dir / '03_content-style_clustering.py'

try:
    import nbformat
    from nbconvert import PythonExporter

    nb_obj = nbformat.read(nb_file.open('r', encoding='utf-8-sig'), as_version=4)
    exporter = PythonExporter()
    body, _ = exporter.from_notebook_node(nb_obj)
    py_out.write_text(body, encoding='utf-8')
except Exception as e:
    py_out = None
    print('Notebook-to-.py export skipped:', e)

print('Export complete:')
print('JSON:', json_path)
print('KMeans plot:', kmeans_plot_path)
print('DBSCAN plot:', dbscan_plot_path)
print('.py script:', py_out)


# --- Code cell 25 ---
# 1. Median performance
work.groupby("dbscan_fixed_cluster")[[
    "engagement_rate",
    "view_rate",
    "view_engagement_rate",
]].median()


# --- Code cell 26 ---
# 2. Sector distribution
pd.crosstab(
    work["dbscan_fixed_cluster"],
    work["sector"],
    normalize="index"
) * 100


# --- Code cell 27 ---
# 4. Top posts per cluster
work.sort_values(
    ["dbscan_fixed_cluster", "engagement_rate"],
    ascending=[True, False]
).groupby("dbscan_fixed_cluster").head(5)[[
    "dbscan_fixed_cluster",
    "sector",
    
    "caption_text",
    "likes_count",
    "comments_count",
    "views_count",
    "engagement_rate",
    "CTA_present",
    "promo_post",
    "mentions_location",
    "religious_theme",
    "patriotic_theme",
    "arabic_dialect_style"
]]


# --- Markdown cell 28 ---
# | Cluster | Meaning / Label                                  | Main Insight                                                                                                                                                                                                 | Recommendation                                                                                                                    |
# | ------- | ------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------- |
# | **-1**  | Mixed expressive / emotional outlier content     | Emotion, emojis, location, and religious/local tone appear strongly, but performance is inconsistent because this group contains mixed outlier-style posts.                                                  | Use emotional and local language more intentionally, but make the message clearer and more consistent.                            |
# | **0**   | Low-effort generic content                       | Short/basic posts with weak CTA, low emojis, low hashtags, and low engagement.                                                                                                                               | Improve captions with stronger hooks, clearer CTA, more personality, and better visual/story value.                               |
# | **1**   | Organic viral personality content                | High engagement without heavy promotion. Success comes from humor, personality, dialect, and relatability.                                                                                                   | Create more authentic, relatable posts instead of over-marketing. Use humor, simple captions, and human tone.                     |
# | **2**   | Full promotional campaign content                | Highly structured posts with CTA, promotion, and location. Good for campaigns but not always highly engaging.                                                                                                | Keep the campaign structure, but add storytelling, emotional hooks, and less direct selling.                                      |
# | **3**   | Hard-selling product/service content             | Promo-heavy posts with no CTA and weak engagement. Mostly direct selling.                                                                                                                                    | Reduce repetitive sales posts. Add customer stories, transformations, reactions, or benefits.                                     |
# | **4**   | Long-form local promotional storytelling content | Long-caption posts combine local identity, emotional/community tone, service details, hashtags, and promotional storytelling. Some perform very well, but some remain weak when they become too sales-heavy. | Keep the local context, clear value, and human tone, but avoid making the caption only a long sales message.                      |
# | **5**   | Aggressive CTA funnel content                    | CTA and promo are very high, but engagement is low because posts push users too quickly toward another platform/action.                                                                                      | Build interest first, then add CTA. Use curiosity, story, value, and local context before asking users to click, watch, or order. |
# 

