/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimilarBusinessRecommendationsSingleRouteImport } from './routes/similar-business-recommendations-single'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as NextPostRecommendationsSingleRouteImport } from './routes/next-post-recommendations-single'
import { Route as MeRouteImport } from './routes/me'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClusterVisualizationRouteImport } from './routes/cluster-visualization'
import { Route as BenchmarkDashboardSingleRouteImport } from './routes/benchmark-dashboard-single'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSimilarRouteImport } from './routes/dashboard.similar'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRecommendationsRouteImport } from './routes/dashboard.recommendations'
import { Route as DashboardRecommendationApisSingleRouteImport } from './routes/dashboard.recommendation-apis-single'
import { Route as DashboardHashtagsRouteImport } from './routes/dashboard.hashtags'
import { Route as DashboardForecastingRouteImport } from './routes/dashboard.forecasting'
import { Route as DashboardForecastSingleRouteImport } from './routes/dashboard.forecast-single'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardClusteringRouteImport } from './routes/dashboard.clustering'
import { Route as DashboardCaptionTipsRouteImport } from './routes/dashboard.caption-tips'
import { Route as DashboardBusinessMomentumSingleRouteImport } from './routes/dashboard.business-momentum-single'
import { Route as DashboardBenchmarkingRouteImport } from './routes/dashboard.benchmarking'
import { Route as DashboardAnomaliesSingleRouteImport } from './routes/dashboard.anomalies-single'

const SimilarBusinessRecommendationsSingleRoute =
  SimilarBusinessRecommendationsSingleRouteImport.update({
    id: '/similar-business-recommendations-single',
    path: '/similar-business-recommendations-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const NextPostRecommendationsSingleRoute =
  NextPostRecommendationsSingleRouteImport.update({
    id: '/next-post-recommendations-single',
    path: '/next-post-recommendations-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterVisualizationRoute = ClusterVisualizationRouteImport.update({
  id: '/cluster-visualization',
  path: '/cluster-visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkDashboardSingleRoute =
  BenchmarkDashboardSingleRouteImport.update({
    id: '/benchmark-dashboard-single',
    path: '/benchmark-dashboard-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimilarRoute = DashboardSimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRecommendationApisSingleRoute =
  DashboardRecommendationApisSingleRouteImport.update({
    id: '/recommendation-apis-single',
    path: '/recommendation-apis-single',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardHashtagsRoute = DashboardHashtagsRouteImport.update({
  id: '/hashtags',
  path: '/hashtags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastingRoute = DashboardForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastSingleRoute = DashboardForecastSingleRouteImport.update({
  id: '/forecast-single',
  path: '/forecast-single',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClusteringRoute = DashboardClusteringRouteImport.update({
  id: '/clustering',
  path: '/clustering',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCaptionTipsRoute = DashboardCaptionTipsRouteImport.update({
  id: '/caption-tips',
  path: '/caption-tips',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessMomentumSingleRoute =
  DashboardBusinessMomentumSingleRouteImport.update({
    id: '/business-momentum-single',
    path: '/business-momentum-single',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBenchmarkingRoute = DashboardBenchmarkingRouteImport.update({
  id: '/benchmarking',
  path: '/benchmarking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnomaliesSingleRoute =
  DashboardAnomaliesSingleRouteImport.update({
    id: '/anomalies-single',
    path: '/anomalies-single',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark-dashboard-single': typeof BenchmarkDashboardSingleRoute
  '/cluster-visualization': typeof ClusterVisualizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/me': typeof MeRoute
  '/next-post-recommendations-single': typeof NextPostRecommendationsSingleRoute
  '/processing': typeof ProcessingRoute
  '/similar-business-recommendations-single': typeof SimilarBusinessRecommendationsSingleRoute
  '/dashboard/anomalies-single': typeof DashboardAnomaliesSingleRoute
  '/dashboard/benchmarking': typeof DashboardBenchmarkingRoute
  '/dashboard/business-momentum-single': typeof DashboardBusinessMomentumSingleRoute
  '/dashboard/caption-tips': typeof DashboardCaptionTipsRoute
  '/dashboard/clustering': typeof DashboardClusteringRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/forecast-single': typeof DashboardForecastSingleRoute
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/hashtags': typeof DashboardHashtagsRoute
  '/dashboard/recommendation-apis-single': typeof DashboardRecommendationApisSingleRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/similar': typeof DashboardSimilarRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark-dashboard-single': typeof BenchmarkDashboardSingleRoute
  '/cluster-visualization': typeof ClusterVisualizationRoute
  '/me': typeof MeRoute
  '/next-post-recommendations-single': typeof NextPostRecommendationsSingleRoute
  '/processing': typeof ProcessingRoute
  '/similar-business-recommendations-single': typeof SimilarBusinessRecommendationsSingleRoute
  '/dashboard/anomalies-single': typeof DashboardAnomaliesSingleRoute
  '/dashboard/benchmarking': typeof DashboardBenchmarkingRoute
  '/dashboard/business-momentum-single': typeof DashboardBusinessMomentumSingleRoute
  '/dashboard/caption-tips': typeof DashboardCaptionTipsRoute
  '/dashboard/clustering': typeof DashboardClusteringRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/forecast-single': typeof DashboardForecastSingleRoute
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/hashtags': typeof DashboardHashtagsRoute
  '/dashboard/recommendation-apis-single': typeof DashboardRecommendationApisSingleRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/similar': typeof DashboardSimilarRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark-dashboard-single': typeof BenchmarkDashboardSingleRoute
  '/cluster-visualization': typeof ClusterVisualizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/me': typeof MeRoute
  '/next-post-recommendations-single': typeof NextPostRecommendationsSingleRoute
  '/processing': typeof ProcessingRoute
  '/similar-business-recommendations-single': typeof SimilarBusinessRecommendationsSingleRoute
  '/dashboard/anomalies-single': typeof DashboardAnomaliesSingleRoute
  '/dashboard/benchmarking': typeof DashboardBenchmarkingRoute
  '/dashboard/business-momentum-single': typeof DashboardBusinessMomentumSingleRoute
  '/dashboard/caption-tips': typeof DashboardCaptionTipsRoute
  '/dashboard/clustering': typeof DashboardClusteringRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/forecast-single': typeof DashboardForecastSingleRoute
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/hashtags': typeof DashboardHashtagsRoute
  '/dashboard/recommendation-apis-single': typeof DashboardRecommendationApisSingleRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/similar': typeof DashboardSimilarRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmark-dashboard-single'
    | '/cluster-visualization'
    | '/dashboard'
    | '/me'
    | '/next-post-recommendations-single'
    | '/processing'
    | '/similar-business-recommendations-single'
    | '/dashboard/anomalies-single'
    | '/dashboard/benchmarking'
    | '/dashboard/business-momentum-single'
    | '/dashboard/caption-tips'
    | '/dashboard/clustering'
    | '/dashboard/content'
    | '/dashboard/forecast-single'
    | '/dashboard/forecasting'
    | '/dashboard/hashtags'
    | '/dashboard/recommendation-apis-single'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/similar'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmark-dashboard-single'
    | '/cluster-visualization'
    | '/me'
    | '/next-post-recommendations-single'
    | '/processing'
    | '/similar-business-recommendations-single'
    | '/dashboard/anomalies-single'
    | '/dashboard/benchmarking'
    | '/dashboard/business-momentum-single'
    | '/dashboard/caption-tips'
    | '/dashboard/clustering'
    | '/dashboard/content'
    | '/dashboard/forecast-single'
    | '/dashboard/forecasting'
    | '/dashboard/hashtags'
    | '/dashboard/recommendation-apis-single'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/similar'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/benchmark-dashboard-single'
    | '/cluster-visualization'
    | '/dashboard'
    | '/me'
    | '/next-post-recommendations-single'
    | '/processing'
    | '/similar-business-recommendations-single'
    | '/dashboard/anomalies-single'
    | '/dashboard/benchmarking'
    | '/dashboard/business-momentum-single'
    | '/dashboard/caption-tips'
    | '/dashboard/clustering'
    | '/dashboard/content'
    | '/dashboard/forecast-single'
    | '/dashboard/forecasting'
    | '/dashboard/hashtags'
    | '/dashboard/recommendation-apis-single'
    | '/dashboard/recommendations'
    | '/dashboard/reports'
    | '/dashboard/similar'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkDashboardSingleRoute: typeof BenchmarkDashboardSingleRoute
  ClusterVisualizationRoute: typeof ClusterVisualizationRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MeRoute: typeof MeRoute
  NextPostRecommendationsSingleRoute: typeof NextPostRecommendationsSingleRoute
  ProcessingRoute: typeof ProcessingRoute
  SimilarBusinessRecommendationsSingleRoute: typeof SimilarBusinessRecommendationsSingleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/similar-business-recommendations-single': {
      id: '/similar-business-recommendations-single'
      path: '/similar-business-recommendations-single'
      fullPath: '/similar-business-recommendations-single'
      preLoaderRoute: typeof SimilarBusinessRecommendationsSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-post-recommendations-single': {
      id: '/next-post-recommendations-single'
      path: '/next-post-recommendations-single'
      fullPath: '/next-post-recommendations-single'
      preLoaderRoute: typeof NextPostRecommendationsSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster-visualization': {
      id: '/cluster-visualization'
      path: '/cluster-visualization'
      fullPath: '/cluster-visualization'
      preLoaderRoute: typeof ClusterVisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark-dashboard-single': {
      id: '/benchmark-dashboard-single'
      path: '/benchmark-dashboard-single'
      fullPath: '/benchmark-dashboard-single'
      preLoaderRoute: typeof BenchmarkDashboardSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/similar': {
      id: '/dashboard/similar'
      path: '/similar'
      fullPath: '/dashboard/similar'
      preLoaderRoute: typeof DashboardSimilarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations': {
      id: '/dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendation-apis-single': {
      id: '/dashboard/recommendation-apis-single'
      path: '/recommendation-apis-single'
      fullPath: '/dashboard/recommendation-apis-single'
      preLoaderRoute: typeof DashboardRecommendationApisSingleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hashtags': {
      id: '/dashboard/hashtags'
      path: '/hashtags'
      fullPath: '/dashboard/hashtags'
      preLoaderRoute: typeof DashboardHashtagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecasting': {
      id: '/dashboard/forecasting'
      path: '/forecasting'
      fullPath: '/dashboard/forecasting'
      preLoaderRoute: typeof DashboardForecastingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecast-single': {
      id: '/dashboard/forecast-single'
      path: '/forecast-single'
      fullPath: '/dashboard/forecast-single'
      preLoaderRoute: typeof DashboardForecastSingleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clustering': {
      id: '/dashboard/clustering'
      path: '/clustering'
      fullPath: '/dashboard/clustering'
      preLoaderRoute: typeof DashboardClusteringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/caption-tips': {
      id: '/dashboard/caption-tips'
      path: '/caption-tips'
      fullPath: '/dashboard/caption-tips'
      preLoaderRoute: typeof DashboardCaptionTipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-momentum-single': {
      id: '/dashboard/business-momentum-single'
      path: '/business-momentum-single'
      fullPath: '/dashboard/business-momentum-single'
      preLoaderRoute: typeof DashboardBusinessMomentumSingleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/benchmarking': {
      id: '/dashboard/benchmarking'
      path: '/benchmarking'
      fullPath: '/dashboard/benchmarking'
      preLoaderRoute: typeof DashboardBenchmarkingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anomalies-single': {
      id: '/dashboard/anomalies-single'
      path: '/anomalies-single'
      fullPath: '/dashboard/anomalies-single'
      preLoaderRoute: typeof DashboardAnomaliesSingleRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnomaliesSingleRoute: typeof DashboardAnomaliesSingleRoute
  DashboardBenchmarkingRoute: typeof DashboardBenchmarkingRoute
  DashboardBusinessMomentumSingleRoute: typeof DashboardBusinessMomentumSingleRoute
  DashboardCaptionTipsRoute: typeof DashboardCaptionTipsRoute
  DashboardClusteringRoute: typeof DashboardClusteringRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardForecastSingleRoute: typeof DashboardForecastSingleRoute
  DashboardForecastingRoute: typeof DashboardForecastingRoute
  DashboardHashtagsRoute: typeof DashboardHashtagsRoute
  DashboardRecommendationApisSingleRoute: typeof DashboardRecommendationApisSingleRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSimilarRoute: typeof DashboardSimilarRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnomaliesSingleRoute: DashboardAnomaliesSingleRoute,
  DashboardBenchmarkingRoute: DashboardBenchmarkingRoute,
  DashboardBusinessMomentumSingleRoute: DashboardBusinessMomentumSingleRoute,
  DashboardCaptionTipsRoute: DashboardCaptionTipsRoute,
  DashboardClusteringRoute: DashboardClusteringRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardForecastSingleRoute: DashboardForecastSingleRoute,
  DashboardForecastingRoute: DashboardForecastingRoute,
  DashboardHashtagsRoute: DashboardHashtagsRoute,
  DashboardRecommendationApisSingleRoute:
    DashboardRecommendationApisSingleRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSimilarRoute: DashboardSimilarRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkDashboardSingleRoute: BenchmarkDashboardSingleRoute,
  ClusterVisualizationRoute: ClusterVisualizationRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MeRoute: MeRoute,
  NextPostRecommendationsSingleRoute: NextPostRecommendationsSingleRoute,
  ProcessingRoute: ProcessingRoute,
  SimilarBusinessRecommendationsSingleRoute:
    SimilarBusinessRecommendationsSingleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
